# Generated by Django 3.0.1 on 2020-01-19 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_Name', models.CharField(max_length=200, unique=True)),
                ('org_code', models.CharField(blank=True, max_length=200)),
                ('at', models.CharField(blank=True, max_length=200)),
                ('po', models.CharField(blank=True, max_length=200)),
                ('block', models.CharField(blank=True, max_length=200)),
                ('sub_division', models.CharField(blank=True, max_length=200)),
                ('ps', models.CharField(blank=True, max_length=200)),
                ('dist', models.CharField(blank=True, max_length=200)),
                ('pin', models.CharField(blank=True, max_length=200)),
                ('state_code', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban ', 'Urban ')], default='Rural', max_length=100)),
                ('map_url', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='org')),
                ('banner_logo', models.ImageField(blank=True, null=True, upload_to='org')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('updated_on', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
