# Generated by Django 3.0.1 on 2020-03-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('smtp_server', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('ssl', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Mail',
                'verbose_name_plural': 'Contact Mail',
            },
        ),
        migrations.CreateModel(
            name='Org_ContactNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=13, unique=True)),
            ],
            options={
                'verbose_name': 'Contacts',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Org_SocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon like fa fa-twitter , fa fa-facebook, fa fa-google-plus, etc', max_length=100)),
                ('css_class', models.CharField(help_text='like ico-twitter , ico-facebook, ico-googleplus, etc', max_length=100)),
                ('activity', models.BooleanField()),
                ('social_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Social',
                'verbose_name_plural': 'Social',
            },
        ),
        migrations.CreateModel(
            name='Org_UsefulLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.URLField()),
            ],
            options={
                'verbose_name': 'Useful Links',
                'verbose_name_plural': 'Useful Links',
            },
        ),
        migrations.CreateModel(
            name='Org_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=200, unique=True)),
                ('org_code', models.CharField(blank=True, max_length=200)),
                ('at', models.CharField(blank=True, max_length=200)),
                ('po', models.CharField(blank=True, max_length=200)),
                ('block', models.CharField(blank=True, max_length=200)),
                ('sub_division', models.CharField(blank=True, max_length=200)),
                ('ps', models.CharField(blank=True, max_length=200)),
                ('dist', models.CharField(blank=True, max_length=200)),
                ('pin', models.IntegerField(blank=True, verbose_name='ZIP / Postal code')),
                ('state', models.CharField(blank=True, max_length=200)),
                ('state_code', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban ', 'Urban ')], default='Rural', max_length=100)),
                ('map_url', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='org')),
                ('banner_logo', models.ImageField(blank=True, help_text='Maximum file size allowed is 200kb && 2000*620 px', null=True, upload_to='org')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('contact_mail', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.ContactMail', verbose_name='Contact Us Mail')),
                ('contact_no', models.ManyToManyField(blank=True, max_length=100, related_name='rel_Org_ContactNo', to='organization.Org_ContactNo')),
                ('social_details', models.ManyToManyField(blank=True, to='organization.Org_SocialDetails')),
                ('useful_link', models.ManyToManyField(blank=True, to='organization.Org_UsefulLinks')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
