# Generated by Django 3.0.1 on 2020-01-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org_ContactNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ph', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Org_SocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon like fa fa-twitter , fa fa-facebook, fa fa-google-plus, etc', max_length=100)),
                ('css_class', models.CharField(help_text='like ico-twitter , ico-facebook, ico-googleplus, etc', max_length=100)),
                ('activity', models.BooleanField()),
                ('social_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Organization Social Details',
                'verbose_name_plural': 'Organization Social Details',
            },
        ),
        migrations.CreateModel(
            name='Org_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_Name', models.CharField(max_length=200, unique=True)),
                ('org_code', models.CharField(blank=True, max_length=200)),
                ('at', models.CharField(blank=True, max_length=200)),
                ('po', models.CharField(blank=True, max_length=200)),
                ('block', models.CharField(blank=True, max_length=200)),
                ('sub_division', models.CharField(blank=True, max_length=200)),
                ('ps', models.CharField(blank=True, max_length=200)),
                ('dist', models.CharField(blank=True, max_length=200)),
                ('pin', models.IntegerField(blank=True, verbose_name='ZIP / Postal code')),
                ('state', models.CharField(blank=True, max_length=200)),
                ('state_code', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, choices=[('Rural', 'Rural'), ('Urban ', 'Urban ')], default='Rural', max_length=100)),
                ('map_url', models.TextField(blank=True, max_length=500)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='org')),
                ('logo1', models.ImageField(blank=True, null=True, upload_to='org')),
                ('banner_logo', models.ImageField(blank=True, null=True, upload_to='org')),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('fax', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('contact_no', models.ManyToManyField(blank=True, max_length=100, related_name='rel_Org_ContactNo', to='organization.Org_ContactNo')),
                ('social_details', models.ManyToManyField(blank=True, max_length=100, related_name='rel_Org_SocialDetails', to='organization.Org_SocialDetails')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
            },
        ),
    ]
