# Generated by Django 3.0.1 on 2020-02-11 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org_details',
            old_name='org_Name',
            new_name='org_name',
        ),
    ]
