# Generated by Django 3.0.1 on 2020-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_ContactNo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ph', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='org_details',
            name='countries',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='org_details',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='org_details',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='org_details',
            name='pin',
            field=models.IntegerField(blank=True, max_length=12, verbose_name='ZIP / Postal code'),
        ),
        migrations.AddField(
            model_name='org_details',
            name='contactn_no',
            field=models.ManyToManyField(blank=True, related_name='rel_Org_Details', to='organization.Org_ContactNo'),
        ),
    ]
