# Generated by Django 3.0.1 on 2020-01-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20200119_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_SocialDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Icon like fa fa-twitter , fa fa-facebook, fa fa-google-plus, etc', max_length=100)),
                ('css_class', models.CharField(help_text='like ico-twitter , ico-facebook, ico-googleplus, etc', max_length=100)),
                ('activity', models.BooleanField()),
                ('social_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'verbose_name': 'Organization Social Details',
                'verbose_name_plural': 'Organization Social Details',
            },
        ),
        migrations.AddField(
            model_name='org_details',
            name='fax',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='org_details',
            name='contactn_no',
            field=models.ManyToManyField(blank=True, related_name='rel_Org_ContactNo', to='organization.Org_ContactNo'),
        ),
        migrations.AlterField(
            model_name='org_details',
            name='pin',
            field=models.IntegerField(blank=True, verbose_name='ZIP / Postal code'),
        ),
        migrations.AddField(
            model_name='org_details',
            name='Social_Details',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='rel_Org_SocialDetails', to='organization.Org_SocialDetails'),
        ),
    ]
