# Generated by Django 3.0.1 on 2020-02-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20200211_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_UsefulLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('links', models.URLField()),
            ],
            options={
                'verbose_name': 'Useful Links',
                'verbose_name_plural': 'Useful Links',
            },
        ),
        migrations.AlterModelOptions(
            name='org_contactno',
            options={'verbose_name': 'Org Contacts', 'verbose_name_plural': 'Org Contacts'},
        ),
        migrations.AlterModelOptions(
            name='org_socialdetails',
            options={'verbose_name': 'Org Social', 'verbose_name_plural': 'Org Social'},
        ),
    ]
