# Generated by Django 3.0.1 on 2020-01-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200120_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_details',
            name='contactn_no',
            field=models.ManyToManyField(blank=True, max_length=100, related_name='rel_Org_ContactNo', to='organization.Org_ContactNo'),
        ),
    ]
