# Generated by Django 3.0.1 on 2020-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20200214_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_details',
            name='social_details',
        ),
        migrations.AddField(
            model_name='org_details',
            name='useful_link',
            field=models.ManyToManyField(blank=True, null=True, to='organization.Org_UsefulLinks'),
        ),
    ]
