# Generated by Django 3.0.1 on 2020-01-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200120_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org_details',
            old_name='contactn_no',
            new_name='contact_no',
        ),
    ]
