# Generated by Django 3.0.1 on 2020-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20200218_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_details',
            name='social_details',
            field=models.ManyToManyField(blank=True, null=True, to='organization.Org_SocialDetails'),
        ),
    ]
