# Generated by Django 3.0.1 on 2020-01-21 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20200120_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='org_details',
            old_name='countries',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='org_details',
            old_name='Social_Details',
            new_name='social_details',
        ),
        migrations.AddField(
            model_name='org_details',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='org_contactno',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
