# Generated by Django 3.0.1 on 2020-03-28 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rel_post_comments', to='post.Post'),
        ),
    ]
