# Generated by Django 3.0.1 on 2020-02-18 06:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20200214_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='position',
            field=models.CharField(choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], default="LEFT", max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
