# Generated by Django 3.0.1 on 2020-02-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20200218_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='position',
            field=models.CharField(choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], default='LEFT', max_length=10),
        ),
    ]
