# Generated by Django 3.0.1 on 2020-02-18 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200218_1146'),
        ('post', '0004_auto_20200218_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(blank=True, help_text="say's that the data will be insert in which Web page", null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Menu'),
        ),
    ]
