# Generated by Django 3.0.1 on 2020-02-18 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200218_1146'),
        ('post', '0005_auto_20200218_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(default=1, help_text="say's that the data will be insert in which Web page", on_delete=django.db.models.deletion.CASCADE, to='page.Menu'),
            preserve_default=False,
        ),
    ]
