# Generated by Django 3.0.1 on 2020-01-08 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20200105_1026'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('post.post',),
        ),
    ]
