# Generated by Django 3.0.1 on 2020-01-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20200108_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='rel_post_galimg', to='post.Gal_Image'),
        ),
    ]
