# Generated by Django 3.0.1 on 2020-01-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20200118_1115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gal_image',
            options={'verbose_name': 'Gallery Images', 'verbose_name_plural': 'Gallery Images'},
        ),
    ]
