# Generated by Django 3.0.1 on 2020-01-21 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200121_2007'),
        ('post', '0011_auto_20200119_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='menu',
            field=models.ForeignKey(default=6, help_text="say's that the data will be insert in which Web page", on_delete=django.db.models.deletion.CASCADE, to='page.Menu'),
            preserve_default=False,
        ),
    ]
