# Generated by Django 3.0.1 on 2020-01-20 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activity', models.BooleanField()),
                ('slug', models.SlugField(default=uuid.uuid4, help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=100, unique=True)),
                ('lvl', models.IntegerField(editable=False, verbose_name='level')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Group',
                'db_table': 'pt_Staff_Group',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('others', 'others')], default='Male', max_length=10)),
                ('dob', models.DateTimeField()),
                ('edu_qualification', models.CharField(max_length=50, verbose_name='Educational Qualification')),
                ('designation', models.CharField(max_length=50, verbose_name='designation / Post')),
                ('opinion', models.TextField(max_length=50)),
                ('contact_no', models.CharField(max_length=13)),
                ('description', models.TextField(max_length=50)),
                ('staff_image', models.ImageField(blank=True, help_text='Maximum file size allowed is 100kb', null=True, upload_to='staff/images/')),
                ('slug', models.SlugField(default=uuid.uuid4, help_text='The name of the page as it will appear in URLs e.g http://domain.com/blog/[my-slug]/', max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Staff_Group', verbose_name='Group Name')),
                ('user', models.OneToOneField(help_text='create user because one user is a one staff', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'db_table': 'pt_Staff',
            },
        ),
    ]
