# Generated by Django 3.0.1 on 2020-01-24 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff_group',
            old_name='activity',
            new_name='is_active',
        ),
    ]
