# Generated by Django 3.0.1 on 2020-01-20 17:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='display_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='contact_no',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='staff',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(blank=True, max_length=50, verbose_name='designation / Post'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='edu_qualification',
            field=models.CharField(blank=True, max_length=50, verbose_name='Educational Qualification'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='opinion',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
