# Generated by Django 3.0.1 on 2020-01-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20200124_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='Gender',
            new_name='gender',
        ),
    ]
