# Generated by Django 3.0.1 on 2020-02-14 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staff_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff_group',
            options={'verbose_name': 'staff-Group', 'verbose_name_plural': 'staff-Group'},
        ),
    ]
