# Generated by Django 3.0.1 on 2020-03-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page_Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('url', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page Template',
                'verbose_name_plural': 'Page Template',
                'db_table': 'Page_Template',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('toolstrip', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, editable=False, max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('lvl', models.IntegerField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('view_title', models.CharField(choices=[('Title', 'Title'), ('Image', 'Image'), ('Both', 'Both')], default='Both', max_length=10)),
                ('icon_class', models.CharField(blank=True, help_text='Enter the Font Awesome icon like fa fa-camera-retro fa-lg,fa fa-home', max_length=100, null=True)),
                ('page_template', models.ForeignKey(help_text='Select Page Template', on_delete=django.db.models.deletion.CASCADE, to='page.Page_Template')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Menu')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'db_table': 'Menu',
            },
        ),
    ]
