# Generated by Django 3.0.1 on 2020-01-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200103_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='view_title',
            field=models.CharField(choices=[('Title', 'Title'), ('Image', 'Image'), ('Both', 'Both')], default='Both', max_length=10),
        ),
    ]
