# Generated by Django 3.0.1 on 2020-02-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200207_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='page_template',
            options={'verbose_name': 'Page Template', 'verbose_name_plural': 'Page Template'},
        ),
        migrations.AlterModelTable(
            name='menu',
            table='Menu',
        ),
        migrations.AlterModelTable(
            name='page_template',
            table='Page_Template',
        ),
    ]
