# Generated by Django 3.0.1 on 2020-03-19 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20200319_1253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu1',
            options={'ordering': ['lvl']},
        ),
    ]
