# Generated by Django 3.0.1 on 2020-01-21 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20200103_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page_template',
            field=models.ForeignKey(blank=True, default=1, help_text='Select Page Template', on_delete=django.db.models.deletion.CASCADE, to='page.Page_Template'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menu',
            name='url',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
