# Generated by Django 3.0.1 on 2020-01-21 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_auto_20200121_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='page_template',
            field=models.ForeignKey(help_text='Select Page Template', on_delete=django.db.models.deletion.CASCADE, to='page.Page_Template'),
        ),
    ]
