# Generated by Django 3.0.1 on 2020-03-20 10:47

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20200320_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('toolstrip', models.CharField(blank=True, max_length=255)),
                ('url', models.CharField(blank=True, editable=False, max_length=255)),
                ('status', models.BooleanField(default=True)),
                ('lvl', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('view_title', models.CharField(choices=[('Title', 'Title'), ('Image', 'Image'), ('Both', 'Both')], default='Both', max_length=10)),
                ('icon_class', models.CharField(blank=True, help_text='Enter the Font Awesome icon like fa fa-camera-retro fa-lg,fa fa-home', max_length=100, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('page_template', models.ForeignKey(help_text='Select Page Template', on_delete=django.db.models.deletion.CASCADE, to='page.Page_Template')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.Menu1')),
            ],
            options={
                'ordering': ['lvl'],
            },
        ),
    ]
