# Generated by Django 3.0.1 on 2020-03-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_menu1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu1',
        ),
    ]
