# Generated by Django 3.0.1 on 2020-03-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_contact_us'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Contact Us', 'verbose_name_plural': 'Contact Us'},
        ),
    ]
