# Generated by Django 3.0.1 on 2020-02-14 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document_File',
        ),
    ]
