# Generated by Django 3.0.1 on 2020-03-16 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='label_color',
            field=models.CharField(choices=[('primary', 'primary'), ('secondary', 'secondary'), ('danger', 'danger')], max_length=10),
        ),
    ]
